### ISSUE TITLE
default value in match doesn't get correctly aligned

### ISSUE THREAD

**Issue by driade** [driade/phpfmt8#19]
```php
$expressionResult = match ($condition) {
    1, 2   => foo(),
default=> baz(),
};
```
instead of
```php
$expressionResult = match ($condition) {
    1, 2   => foo(),
    default => baz(),
};
```

**Comment by glauca** [comment]
> ```
> $expressionResult = match ($condition) {
>     1, 2   => foo(),
> default=> baz(),
> };
> ```
> 
> instead of
> 
> ```
> $expressionResult = match ($condition) {
>     1, 2   => foo(),
>     default => baz(),
> };
> ```

Have you solved it?

**Comment by driade** [comment]
@glauca still on it, sorry

**Comment by driade** [comment]
@glauca there you're ;)

**Comment by driade** [comment]
my bad, is not

**Comment by driade** [comment]
Done, it's been harder than I expected
