### ISSUE TITLE
Format error with passes

### ISSUE THREAD

**Issue by kokororin** [driade/phpfmt8#27]
When running cmd:
```
php fmt.stub.php --psr2 --indent_with_space=4 --passes=SpaceAfterExclamationMark --exclude=PSR2ModifierVisibilityStaticOrder
```
it prints `Could not open input file: xxx/fmt-external.stub.php`

**Comment by driade** [comment]
Hello, good morning.

Thanks for opening the issue. It made me realize the original phpfmt package has a way to execute additional rules via and external script. **Thus, the rule SpaceAfterExclamationMark doesn't exists in the current phpfmt implementation.** I've seen some references to it on Google, but no code I could inspect.

It may have been supported in the past but I don't hace access to that code. It seems other formatters have this rule.

**I've suggest you to try the rule SpaceAroundExclamationMark**, which may fit your needs.

The other way around, I/we could create this rule in the current phpfmt implementation, though I'd need to know what should it do, exactly.

Thanks!

cc https://github.com/kokororin/vscode-phpfmt/issues/104

**Comment by driade** [comment]
Hi again! I've seen https://github.com/kokororin/vscode-phpfmt/issues/104

I'd be nice to know where the SpaceAfterExclamationMark comes from.

Thanks!

**Comment by driade** [comment]
@kokororin May I have access to https://github.com/kokororin/fmt so I can try to merge the missing rules?

**Comment by kokororin** [comment]
This repo has not been updated for 5 years, but I can give you access.

**Comment by driade** [comment]
Thanks! I'm already integrating it ;)

**Comment by driade** [comment]
Done https://github.com/driade/phpfmt8/releases/tag/v834.0.0 Now if everyone updates their packages the fix should be ready.

I don't now your update process, if https://github.com/lucasferreira/node-use-phpfmt should be updated to pick the changes, etc.

**Comment by driade** [comment]
I'd also suggest to update the Readme to recover this two packages.

**Comment by kokororin** [comment]
Quick fix ! Thanks.

**Comment by driade** [comment]
Ho @kokororin good morning. Would you like me to help you with some issues I've seen in your repo relating this package? I'd answer the directly there if you want.

**Comment by kokororin** [comment]
@driade Thanks, I'm traveling and can't reply in time, thank you for your help.

**Comment by driade** [comment]
Would you find it ok if I invite the people that have opened issues about formatting to open the issue here?

**Comment by kokororin** [comment]
@driade Of course, please go ahead
