### ISSUE TITLE
Issues with formatting of Arrays and Array Access for WordPress Coding Standards

### ISSUE THREAD

**Issue by nisarul-media** [driade/phpfmt8#33]
### Issues:

1. As per WordPress Coding Standard, an array should be defined like this: (space at the beginning and closing of parentheses or square brackets)
![Screenshot 2023-05-30 at 10 09 59 AM](https://github.com/kokororin/vscode-phpfmt/assets/65971192/b9e51f0e-ffe1-4fda-94ba-bb12e326d7a4)
Source: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays

2. As per WordPress Coding Standard, spaces while accessing array items will be like this:
![Screenshot 2023-05-30 at 10 06 16 AM](https://github.com/kokororin/vscode-phpfmt/assets/65971192/4f98159a-4b1c-40aa-ba08-0244b850fdba)
Source: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage

Please, solve this issue by introducing some configurations regarding "[]"  (Square brackets) so that WordPress Developers can write PHP and use the vscode-phpfmt with more ease.

Thank you.

**Comment by driade** [comment]
Hi, there you're. I've just pushed an initial release for WP which works like PSR2 with the difference you asked for.

I'm going to coordinate with the vscode team for the update to be available, this package is mostly intended to work with Sublime Text.

Thanks!
