### ISSUE TITLE
Add auto semicolon after anonymous class

### ISSUE THREAD

**Issue by driade** [driade/phpfmt8#44]
```php
$instance = new class {}
```

should become

```php
$instance = new class {};
```

**Comment by arcanisgk** [comment]
yes i can confirm that

**Comment by driade** [comment]
I'm going to close this one because I'm unable to reproduce it now. @arcanisgk could you please double check on your side? With AutoSemicolon I see it's working fine on my side.

**Comment by arcanisgk** [comment]
This happens when you implement:

```
"passes":
    [
        "RemoveSemicolonAfterCurly",
    ],
```
