### ISSUE TITLE
Format HTML inside PHP file

### ISSUE THREAD

**Issue by ahmadyogi543** [driade/phpfmt8#64]
Hi, first of all thanks for the great project, it help me a lot to format my PHP code. I just wondering how can I use this formatter to format HTML inside the PHP file. I already try use it but the HTML doesn't get formatted. How can we do this?

Thanks in advance and sorry for my bad english 😄

**Comment by driade** [comment]
Hi @ahmadyogi543 , sorry for the delay. This package just formats PHP, not HTML. It also formats PHP inside HTML, such as

```
<html>
<?php
    echo "hola";
?>
</html>
```

but not the html itself
