### ISSUE TITLE
Formatting not working, error in "Troubleshoot Information" message

### ISSUE THREAD

**Issue by AlexanderCecile** [driade/phpfmt8#66]
The basic formatting command doesn't seem to do anything. The popup from the "Troubleshoot Information" command itself contains an error message:

```
phpfmt (php version):
PHP 8.2.4 (cli) (built: Apr  6 2023 08:21:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies

phpfmt (php tokenizer) found

phpfmt (fmt.stub.php version):
Could not open input file: /Users/******/Library/Application Support/Sublime Text/Packages/phpfmt/fmt.stub.php
```

I didn't notice anything obviously wrong with the `fmt.stub.php` file, nor have I touched it since installation. What could be the issue here?

Thank you :)

**Comment by driade** [comment]
Hi @AlexanderCecile 

The package hasn't been updated for a few months, so it shouldn't throw any new error. I'd suggest reinstalling the package and see if it works.

Thanks!
