### ISSUE TITLE
Problems with spaces when formatting

### ISSUE THREAD

**Issue by reprintsev** [driade/phpfmt8#68]
When using the `--exclude=AddMissingCurlyBraces` option, the space between the closing parenthesis and next statement is removed

```php
<?php
if (true) return;
```
becomes

```php
<?php
if (true)return;
```

When using the `--exclude=MergeParenCloseWithCurlyOpen` option, an extra space is added before `else`

```php
<?php
if (true) {
    // something
}
else {
    // something
}
```

becomes

```php
<?php
if (true) {
    // something
}
 else {
    // something
}
```

**Comment by driade** [comment]
Thanks, I'll check it

**Comment by driade** [comment]
Thank you @reprintsev this should be already fixed in the latest release. May you please confirm?

**Comment by reprintsev** [comment]
@driade yes, the problem is solved, thanks!
