### ISSUE TITLE
Manjaro Linux php 8.3 process of reverting to 8.2

### ISSUE THREAD

**Issue by mpmont** [driade/phpfmt8#72]
Hi there. 

On the last version of Manjaro Linux the php executable upgraded to 8.3. 
That added a few problems into the fmt Package that I will report on other issues. 

To revert this process I installed php8.2 alongside 8.3 and pointed the executable to it. 

However the plugin does not complain saying it does not find the binary but it does not work at all. 

Tried to run it with the console to see if there's any error but nothing. 

So I ran fmt troubleshoot information and I thing I got something. 

When I point to the 8.2 binary this is what I get: 

![Screenshot_20240321_095330](https://github.com/driade/phpfmt8/assets/537664/3c1b16ce-a4a3-42ee-9add-9503cb3006f0)

Something about that constant not being defined.

**Comment by mpmont** [comment]
Do I need to install something more than than vanilla php82 for it to work?

**Comment by driade** [comment]
Hi @mpmont . No, you shouldn't need any more than the binary. May you please confirm this?

https://www.php.net/manual/es/tokenizer.installation.php

So, knowing if php is compiled with the builtn tokenizer.

```
php -i|grep [tT]oke
```

**Comment by driade** [comment]
>That added a few problems into the fmt Package that I will report on other issues.

Waiting for them, thanks!
