### ISSUE TITLE
New Transformation: AlignHashComments

### ISSUE THREAD

**Issue by phuze** [driade/phpfmt8#76]
Could we add a new transformation option for hash comments, that would behave similar to [AlignDoubleSlashComments](https://github.com/driade/phpfmt8/blob/master/fmt.stub.php#L7250)?

Example:
```php
//From:
$a = 1; # Comment 1
$bb = 22;  # Comment 2
$ccc = 333;  # Comment 3

//To:
$a = 1;      # Comment 1
$bb = 22;    # Comment 2
$ccc = 333;  # Comment 3
```

**Comment by driade** [comment]
Hi @phuze , good morning. I'll try to take it a look.

**Comment by phuze** [comment]
Hi, and thank you 🙏.

I'll mention there was a change in PHP 8 onwards, where `#[` marks the beginning of an [attribute](https://www.php.net/manual/en/language.attributes.overview.php). Anything else is still treated as a comment.

```php
class VersionedObject
{
    #[JsonSerialize]   # attribute example
    public const version = '0.0.1';
}
```

**Comment by driade** [comment]
Thank you. Could you please elaborate this last message? We're is the bug?

**Comment by phuze** [comment]
My example was demonstrating the particular meaning of `#[`, not suggesting a bug. I thought it was worth mentioning, incase it could be of concern when parsing within phpfmt.

Hash comments (`# hello`) are otherwise [parsed the same](https://github.com/php/php-src/blob/ea1ea33bd5d967e9c04046c1af869e4e8b53116e/Zend/zend_language_scanner.l#L2050) as double slash comments (`// hello`).

I wonder if we could rename [AlignDoubleSlashComments](https://github.com/driade/phpfmt8/blob/master/fmt.stub.php#L7250) to simply `AlignComments`, and make a small adjustment to support `#` comments.

Example: https://github.com/phuze/phpfmt8/commit/df7e3637681dfdc1b269c04efba2adbe47f4d4da

**Comment by phuze** [comment]
I tested the [change](https://github.com/phuze/phpfmt8/commit/df7e3637681dfdc1b269c04efba2adbe47f4d4da) by modifying my local vscode extension, and I can confirm it seems to work as intended.
Extension file:  `%USERPROFILE%\.vscode\extensions\kokororin.vscode-phpfmt-1.2.10\dist\fmt.stub.php`

**Before**:
![image](https://github.com/driade/phpfmt8/assets/9218035/1ff5f418-842a-4f71-a5a1-0ba25b90c870)

**After**:
![image](https://github.com/driade/phpfmt8/assets/9218035/f13c4804-8f7c-4bb0-9544-3135c45ce332)

**Comment by driade** [comment]
Thank you! I've integrated your code, added some tests, and it's already added to the repo. The main difference is that we shouldn't rename an existing rule, because all the people that it's already using it would lose it.
