### ISSUE TITLE
Switch statement

### ISSUE THREAD

**Issue by Tomirad** [driade/phpfmt8#81]
Hello,

I have code:

```
switch ($role) {
	case Role::SUPER_ADMIN:
	case Role::ADMIN:
		$url = '/admin-panel';
		break;
	case Role::DIRECTOR:
		$url = '/director-panel';
		break;
	case Role::ACCOUNTANT:
		$url = '/billing-panel';
		break;
	default:
		$url = '/guest-panel';
}
```

but after using this package I have removed indentation.
```
switch ($role) {
case Role::SUPER_ADMIN:
case Role::ADMIN:
	$url = '/admin-panel';
	break;
case Role::DIRECTOR:
	$url = '/director-panel';
	break;
case Role::ACCOUNTANT:
	$url = '/billing-panel';
	break;
default:
	$url = '/guest-panel';
}
```
What can I do to prevent it from removing indents?

**Comment by Tomirad** [comment]
`enum { case; }` also too.

**Comment by driade** [comment]
Hi @Tomirad This is quite strange. May you please share your config (what rules are you using)?

**Comment by Tomirad** [comment]
My conf for phpftm is it:
`{    "php_bin": "W:\\WebServer\\php\\php8.3\\php.exe" }`
That is, the basic thing.

I'm using this in Sublime Text 4169 - no license, Windows 11

Other package is:
ApacheConf, Folder Aliaser, FTPSync, Function Name Display, Git, GitStatus, Goto-CSS-Declaration, GoToClass, hex to Int Preview, HexViewer, HTMLBeautify, JavaScript Beautify, Json Colors And Navigation, MikrotikScript, Minifi, nginx, Paradox, PHP Codebeautyfier, phpfmt, PHPIntel, Pretty JSON, Print to HTML, SFTP, SideBarEnhancements, SqlBeautyfier, Squirrel, Status Bar JsonPath, StatusMessage, Theme -  Monokai Pro, WakaTime, xml2json.

But, on other PC with fewer add-ons this also occurs. Practically only SFTP, Wakatime and phpfmt and PHPIntel. 

When I disabled **phpfmt**, this problem did not occur.

**Comment by driade** [comment]
Hi. Could you please activate try with this config and see if it still happens? Thank you

```json
{
    "autocomplete": false,
    "autoimport": false,
    "excludes": [
        "SpaceBetweenMethods"
    ],
    "format_on_save": true,
    "passes":
    [
        "AlignDoubleArrow",
        "AlignPHPCode",
        "SpaceAfterExclamationMark",
        "AlignConstVisibilityEquals",
        "AutoSemicolon",
        "ConvertOpenTagWithEcho",
        "AlignEquals",
        "MergeNamespaceWithOpenTag",
        "RemoveSemicolonAfterCurly",
        "RestoreComments",
        "ShortArray",
        "ExtraCommaInArray",
        "AlignDoubleSlashComments"
    ],
    "php_bin": "YOUR_PHP_PATH",
    "psr1": false,
    "psr1_naming": true,
    "psr2": true,
    "readini": true,
    "smart_linebreak_after_curly": false,
    "version": 4,
    "wp": false,
}
```

Please check for the "php_bin" path

**Comment by Tomirad** [comment]
I activated it. Now the indentation does not go back.

I found that **"psr2": false** caused the lines to lose indentation.

Thanks!
