### ISSUE TITLE
Prevent align vertical by scope

### ISSUE THREAD

**Issue by karchung0930** [driade/phpfmt8#89]
Hi, so far it formated my code as:
```
'enabled'              => [
    'title' => 'Enable/Disable',
],
'test_publishable_key' => [
    'aaa'        => 'first',
    'aaabbbccc'  => 'second',
],
```
The first array `enabled` is being align with its next scope `test_publishable_key`. Personally I think this looks weird. How do I prevent it from formatting this by scope so it looks like:
```
'enabled' => [
    'title' => 'Enable/Disable',
],
'test_publishable_key' => [
    'aaa'        => 'first',
    'aaabbbccc'  => 'second',
],
```
Reference: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/operator/binary_operator_spaces.rst#example-10

Any option for this?

**Comment by driade** [comment]
Hi @karchung0930 . Maybe removing the rule AlignDoubleArrow will help us. May you please confirm?

**Comment by driade** [comment]
Hi @karchung0930 , understood. There're no plans at this moment to modify the behaviour of this rule. Also, please consider that this package has nothing to be with PHP CS Fixer.
